### ISSUE TITLE
last.fm

### ISSUE THREAD

**Issue by taizilongxu** [skyline75489/pyfm#12]
fm.py 中的Scrobbler(self.last_fm_username, self.last_fm_password)

这个 password 是原始密码还是 md5 后的密码?

我调用了一下都没登陆上,求解!

**Comment by skyline75489** [comment]
是 md5 之后的

**Comment by taizilongxu** [comment]
好的,我再试试

**Comment by taizilongxu** [comment]
用户名搞错了,以为是邮箱, OK
